version: '3'
services:
  app:
    container_name: rest-api
    build: .
    command: npm run dev
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - './:/usr/src/app'
    networks:
      - node_stack

  mongo:
    container_name: rest-api-db
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - node_stack

networks:
  node_stack:
    driver: bridge
